const Sidebar = () => {
  return (
    <aside className="w-full h-[80%] max-h-[80%] bg-green-600 overflow-auto">
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
      <div>INFO</div>
    </aside>
  );
};

export default Sidebar;
